name: Process CSV and Generate SQL

on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 */6 * * *'
  workflow_dispatch:

jobs:
  process_csv:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install pandas
        sudo apt-get install unzip wget

    - name: Download and unzip CSV
      run: |
        wget https://github.com/NikolaiT/IP-Address-API/raw/main/databases/geolocationDatabaseIPv4.csv.zip
        unzip geolocationDatabaseIPv4.csv.zip

    - name: Process CSV and Generate SQL
      run: python script.py

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add db1.sql.gz
        git add db2.sql.gz
        git commit -m "Add generated SQL file"
        git push
